runtime: python311

entrypoint: gunicorn backend.wsgi:application

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: backend.settings
  SECRET_KEY: "django-insecure-i3wv!f@d@2cz*@3*@xfd(=&$kh@uo)@qst$g)x-&!lx(@wd)+d"
  DEBUG: "False"

handlers:
  - url: /static
    static_dir: staticfiles/

  - url: /.*
    script: auto
